### Получить все заметки
GET http://localhost:3000/notes

###

### Получить одну заметку по ID (подставь свой ID из базы)
GET http://localhost:3000/notes/699f20832f29257467472b49

###

### Создать новую заметку
POST http://localhost:3000/notes
Content-Type: application/json

{
  "title": "Выучить MongoDB",
  "content": "Разобраться с коллекциями и схемами",
  "tag": "Work"
}
###
DELETE http://localhost:3000/notes/699f20832f29257467472b49
